CREATE DATABASE IF NOT EXISTS ESP;
USE ESP;
CREATE TABLE IF NOT EXISTS temperature(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    temperature FLOAT
);
CREATE TABLE IF NOT EXISTS pressure(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pressure FLOAT
);
INSERT INTO temperature VALUES (0,1.3) ;
INSERT INTO temperature VALUES (3,2) ;
INSERT INTO pressure VALUES (0,1.3) ;

SELECT * FROM temperature;
SELECT * FROM pressure;